events {}

http {
    upstream web_backend {
        # Nome do serviço "api" em docker-compose.yml (raiz do monorepo).
        server api:8000;
    }

    server {
        listen 90;

        location / {
            proxy_pass http://web_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
    }
}
