name: CI for FastAPI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  aviso:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Exibir aviso
      run: "echo \"🚨 Aviso: O workflow foi executado, sem testes ou deploy. 🚨\""

