apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DATABASE_URL: postgres://your_user:your_password@postgres_db:5432/your_db
  JWT_REFRESH_SECRET: your_refresh_jwt_secret
  JWT_SECRET: your_jwt_secret
  POSTGRES_PASSWORD: your_password
