apiVersion: v1
data:
  JWT_EXPIRATION: "3600"
  JWT_REFRESH_EXPIRATION: "86400"
  POSTGRES_DB: your_db
  POSTGRES_USER: your_user
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: db-db-env
  name: db-env
