apiVersion: v1
data:
  DATABASE_URL: postgres://your_user:your_password@postgres_db:5432/your_db
  JWT_EXPIRATION: "3600"
  JWT_REFRESH_EXPIRATION: "86400"
  JWT_REFRESH_SECRET: your_refresh_jwt_secret
  JWT_SECRET: your_jwt_secret
  POSTGRES_DB: your_db
  POSTGRES_PASSWORD: your_password
  POSTGRES_USER: your_user
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: awlicite-api-awlicite-api-env
  name: awlicite-api-env
