apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: awlicite-api
  name: awlicite-api
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: awlicite-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: awlicite-api
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: awlicite_api-env
            - name: JWT_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  key: JWT_EXPIRATION
                  name: awlicite_api-env
            - name: JWT_REFRESH_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  key: JWT_REFRESH_EXPIRATION
                  name: awlicite_api-env
            - name: JWT_REFRESH_SECRET
              valueFrom:
                configMapKeyRef:
                  key: JWT_REFRESH_SECRET
                  name: awlicite_api-env
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET
                  name: awlicite_api-env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: awlicite_api-env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: awlicite_api-env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: awlicite_api-env
            - name: PYTHONPATH
              value: /app
          image: awlicite-api
          name: awlicite-api
      restartPolicy: Always
